### ISSUE TITLE
End points of lines are not found as intersecting points

### ISSUE THREAD

**Issue by FliegendeWurst** [ucarion/line_segment_intersection#1]
unique_intersection() does not find the intersection of these LineIntervals:

LineInterval { line: Line { start: Point(Coordinate { x: **140**, y: **40** }), end: Point(Coordinate { x: 90, y: 160 }) }, interval_of_intersection: (0, 1) }
LineInterval { line: Line { start: Point(Coordinate { x: 70, y: 120 }), end: Point(Coordinate { x: **140**, y: **40** }) }, interval_of_intersection: (0, 1) }

Is this intentional?

**Comment by ucarion** [comment]
Hey, sorry for the late reply.

I suspect you're running into a floating-point issue. One solution you may want to consider is expanding the "interval of intersection" to be something like `(0 - delta, 1 + delta)`, for some small `delta`.

**Comment by ucarion** [comment]
Closing, since I assume this solution would have worked for you.

If it did not, @FliegendeWurst please re-open. :)
